package imagebuilder

import (
	"fmt"
	"strings"
)

// GuestHomeDir is the platform convention for where the durable home
// volume gets mounted inside the guest — a fixed path rather than trying to
// honor whatever $HOME the original image happened to use, the same kind
// of fixed-convention choice as the guest_port decision in §4.3. Exported
// so the Controller/Host Agent side could reference it if needed later.
const GuestHomeDir = "/home/agent"

// BuildInitScript generates the guest's /sbin/init (§4.6 step 4). Since
// networking is already fully handled by the kernel's own `ip=` boot
// argument (§4.3) — zero guest-side cooperation needed for that — init has
// two remaining jobs: mount the durable home volume, and configure the
// egress proxy (§4.8) before exec'ing the customer's original entrypoint.
//
// The Squid proxy address isn't known at image-build time — it depends on
// this instance's subnet allocation, decided later, at boot (§4.3's
// VMManager appends it to the kernel command line as
// platform.squid_proxy=host:port). Init reads it from /proc/cmdline rather
// than having it baked into the image.
//
// Known limitation, deliberately not solved here: this requires a POSIX
// shell in the base image. A `FROM scratch` image with a single static
// binary and no shell at all won't work — flagging this rather than
// silently producing a broken rootfs; fine for a prototype, a real
// platform would need a static init binary instead of a shell script.
func BuildInitScript(entrypoint []string) (string, error) {
	if len(entrypoint) == 0 {
		return "", fmt.Errorf("empty entrypoint")
	}
	quoted := make([]string, len(entrypoint))
	for i, arg := range entrypoint {
		quoted[i] = shellQuote(arg)
	}
	return fmt.Sprintf(`#!/bin/sh
# Generated by the platform's Image Builder (design doc §4.6). Guest
# networking is already configured by the kernel's own ip= boot argument —
# nothing to do here for that.
set -e
# /proc isn't mounted automatically (unlike /dev, which the kernel mounts
# itself via devtmpfs) — needed below to read the Squid proxy address off
# the kernel command line. Without it, that read fails, and since this
# script runs as PID 1 under set -e, the failure exits init itself, which
# the kernel treats as fatal ("Attempted to kill init!") — confirmed against
# a real boot: the guest panicked here before ever reaching the entrypoint.
mount -t proc proc /proc
mkdir -p %s
mount -t ext4 /dev/vdb %s
export HOME=%s

# Egress proxy (§4.8): Squid enforces the workload's allowlist via ACLs on
# the CONNECT method, so HTTPS works without decrypting anything (no
# SSL-bump, no cert-trust setup needed in the guest). The address is set by
# the Host Agent per-instance at boot time, not baked into this image.
SQUID_PROXY=$(sed -n 's/.*platform\.squid_proxy=\([^ ]*\).*/\1/p' /proc/cmdline)
if [ -n "$SQUID_PROXY" ]; then
  export HTTP_PROXY="http://$SQUID_PROXY"
  export HTTPS_PROXY="http://$SQUID_PROXY"
  export http_proxy="http://$SQUID_PROXY"
  export https_proxy="http://$SQUID_PROXY"
fi

cd "$HOME"
exec %s
`, GuestHomeDir, GuestHomeDir, GuestHomeDir, strings.Join(quoted, " ")), nil
}

// shellQuote wraps an argument in single quotes for safe inclusion in the
// generated init script, escaping any embedded single quotes.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
